MODEL:
  META_ARCHITECTURE: "CenterMask"
  MASK_ON: True
  PIXEL_MEAN: [ 0.408, 0.447, 0.470 ]
  PIXEL_STD: [ 0.289, 0.274, 0.278 ]
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: [ 512, 512 ]
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_val")
  TEST: ("coco_2014_minival",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2.5e-4
  STEPS: (210000, 250000)
  MAX_ITER: 270000
#TEST:
#  EVAL_PERIOD: 1
VERSION: 2