MODEL:
  META_ARCHITECTURE: "CenterMask"
  MASK_ON: True
  PIXEL_MEAN: [ 0.408, 0.447, 0.470 ]
  PIXEL_STD: [ 0.289, 0.274, 0.278 ]
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_val")
  TEST: ("coco_2014_minival",)
SOLVER:
  IMS_PER_BATCH: 128
  BASE_LR: 2.5e-4
  STEPS: (95500, 114600)
  MAX_ITER: 124150
#TEST:
#  EVAL_PERIOD: 1
VERSION: 2