MODEL:
  META_ARCHITECTURE: "CenterMask"
  MASK_ON: True
  PIXEL_MEAN: [ 0.408, 0.448, 0.471 ]
  PIXEL_STD: [ 0.242, 0.239, 0.234 ]
INPUT:
  MASK_FORMAT: "bitmask"
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_val")
  TEST: ("coco_2014_minival",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 2.5e-4
  STEPS: (382000, 458400)
  MAX_ITER: 496600
#TEST:
#  EVAL_PERIOD: 1
VERSION: 2