_BASE_: "base.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_val")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)