_BASE_: "base.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
OUTPUT_DIR: "./output/faster_voc"