from detectron2.config import CfgNode as CN


def add_center_config(cfg):
    """
    Add config for CenterMask.
    """
    _C = cfg

    _C.MODEL.CENTER_MASK = CN()
    _C.MODEL.CENTER_MASK.NUM_CLASSES = 80
    _C.MODEL.CENTER_MASK.S = 32
    _C.MODEL.CENTER_MASK.NORM = "BN"
    _C.MODEL.CENTER_MASK.FOCAL_LOSS_ALPHA = 2.0
    _C.MODEL.CENTER_MASK.FOCAL_LOSS_GAMMA = 4.0
    _C.MODEL.CENTER_MASK.LAMBDA_P = 1.0
    _C.MODEL.CENTER_MASK.LAMBDA_OFF = 1.0
    _C.MODEL.CENTER_MASK.LAMBDA_SIZE = 0.1
    _C.MODEL.CENTER_MASK.LAMBDA_MASK = 1.0
    _C.MODEL.CENTER_MASK.SCORE_THRESH_TEST = 0.05
    _C.MODEL.CENTER_MASK.MASK_THRESH_TEST = 0.4
    _C.MODEL.CENTER_MASK.TOP_K_CANDIDATES_TEST = 100
